FROM python:3.10-slim

# Install system-level dependencies
RUN apt-get update && \
    apt-get install -y \
      ffmpeg \
      libgl1-mesa-glx \
      libglib2.0-0 \
      libsm6 \
      libxext6 \
      build-essential \
      libxrender1 && \
    rm -rf /var/lib/apt/lists/*

COPY mmct/ mmct/
COPY pyproject.toml .
COPY requirements.txt .

RUN pip install --upgrade pip>=24.3
RUN pip install --no-cache-dir -r requirements.txt